version: "3.9"

services:
  # Django Backend
  django_backend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    image: university_system_backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONBUFFERED=1
    command:
      [
        "sh",
        "-c",
        "python backend/manage.py spectacular --color --file backend/schema.yml && python backend/manage.py collectstatic --noinput && python backend/manage.py makemigrations && python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000",
      ]
    volumes:
      - .:/code # For hotreloading
    depends_on:
      - redis
      - postgres

  # Redis Server
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"

  postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

volumes:
  university_system:
