# Generated by Django 5.0 on 2024-01-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_entries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmententry',
            name='is_hiring_staff',
            field=models.BooleanField(default=False),
        ),
    ]
